apiVersion: apps/v1
kind: Deployment # Deployment kommer att se till containers skapas 
metadata:
  name: goapiperf
  labels:
    app: goapiperf
spec:
  replicas: 1 #scale out!!!!
  selector:
    matchLabels:
      app: goapiperf
  template:
    metadata:
      labels:
        app: goapiperf
    spec:
      containers:
        - name: goapiperf
          image: git.systementor.se/yacloud/goapiperf
          ports:
            - containerPort: 8080
          env:
            - name: GIN_MODE
              value: release
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              cpu: 40m
              memory: 32Mi          
---
apiVersion: v1
kind: Service
metadata:
  name: goapiperf-service
  labels:
    app: goapiperf
spec:
  type: ClusterIP # LoadBalancer skapar en extern IP-adress som kan nås från internet
  ports:
  - name: http
    port: 80 # 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: goapiperf
  sessionAffinity: None