apiVersion: apps/v1
kind: Deployment # Deployment kommer att se till containers skapas 
metadata:
  name: aspnetapiperf
  labels:
    app: aspnetapiperf
spec:
  replicas: 1 #scale out!!!!
  selector:
    matchLabels:
      app: aspnetapiperf
  template:
    metadata:
      labels:
        app: aspnetapiperf
    spec:
      containers:
        - name: aspnetapiperf
          image: git.systementor.se/yacloud/aspnetperfapi
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 20m
              memory: 32Mi    
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapiperf-service
  labels:
    app: aspnetapiperf
spec:
  type: ClusterIP # LoadBalancer skapar en extern IP-adress som kan nås från internet
  ports:
  - name: http
    port: 80 # 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: aspnetapiperf
  sessionAffinity: None