apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration-9hghh7d6bd
  labels:
    name: prometheus-configuration-9hghh7d6bd
  namespace: ingress-nginx
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:

      - job_name: 'kubernetes-cadvisor'
        scheme: http
        kubernetes_sd_configs:
        - api_servers:
          - https://kubernetes.default.svc
          in_cluster: true
          role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        # Use cadvisor 4194 port
        - source_labels: [__address__]
          regex: '(.*):10250'
          replacement: '${1}:4194'
          target_label: __address__

        # Backward compatibility for Kubernetes 1.3 dashboards
        metric_relabel_configs:
        - source_labels: [io_kubernetes_container_name,container_name]
          action: replace
          regex: (.*);(.*)
          replacement: '${1}${2}'
          target_label: io_kubernetes_container_name
        - source_labels: [kubernetes_pod_name,pod_name]
          action: replace
          regex: (.*);(.*)
          replacement: '${1}${2}'
          target_label: kubernetes_pod_name
        - source_labels: [kubernetes_pod_name]
          action: replace
          target_label: io_kubernetes_pod_name

      - job_name: 'ingress-nginx-endpoints'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - ingress-nginx
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\\d+)?;(\\d+)
          replacement: $1:$2
        - source_labels: [__meta_kubernetes_service_name]
          regex: prometheus-server
          action: drop
    
